export default function Privacy() {
    return (
        <main className="text-xs bg-primary p-4 text-tp">
            <section className="p-14 rounded-lg">
                <div className="container rounded-lg">
                    <h1 className="text-3xl font-bold mb-6 text-accent">Privacy Policy</h1>
                    <p className="text-xl py-4">Last updated: September 19, 2024</p>
                    <p className="mb-4">
                        This Privacy Policy describes Our policies and procedures on the collection, use, and
                        disclosure of Your information when You use the Service and tells You about Your privacy
                        rights and how the law protects You.
                    </p>
                    <p className="mb-4">
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree
                        to the collection and use of information in accordance with this Privacy Policy. This Privacy
                        Policy has been created with the help of the
                        <a
                            href="https://www.termsfeed.com/privacy-policy-generator/"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-accent underline"
                        >
                            Privacy Policy Generator
                        </a>.
                    </p>

                    <h2 className="text-2xl font-semibold mt-6 mb-4">Interpretation and Definitions</h2>

                    <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
                    <p className="mb-4">
                        The words of which the initial letter is capitalized have meanings defined under the following
                        conditions. The following definitions shall have the same meaning regardless of whether they
                        appear in singular or in plural.
                    </p>

                    <h3 className="text-xl font-semibold mb-2">Definitions</h3>
                    <p className="mb-2">For the purposes of this Privacy Policy:</p>
                    <ul className="list-disc list-inside space-y-2 opacity-75">
                        <li>
                            <strong>Account</strong> means a unique account created for You to access our Service or
                            parts of our Service.
                        </li>
                        <li>
                            <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under
                            common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares,
                            equity interest, or other securities entitled to vote for election of directors or other
                            managing authority.
                        </li>
                        <li>
                            <strong>Company</strong> (referred to as either &apos;the Company&apos;, &apos;We&apos;, &apos;Us&apos; or &apos;Our&apos; in this
                            Agreement) refers to welllmake.
                        </li>
                        <li>
                            <strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or
                            any other device by a website, containing details of Your browsing history on that website.
                        </li>
                        <li>
                            <strong>Country</strong> refers to: Delhi, India.
                        </li>
                        <li>
                            <strong>Device</strong> means any device that can access the Service such as a computer, a
                            cellphone, or a digital tablet.
                        </li>
                        <li>
                            <strong>Personal Data</strong> is any information that relates to an identified or
                            identifiable individual.
                        </li>
                        <li>
                            <strong>Service</strong> refers to the Website.
                        </li>
                        <li>
                            <strong>Service Provider</strong> means any natural or legal person who processes the data
                            on behalf of the Company.
                        </li>
                        <li>
                            <strong>Usage Data</strong> refers to data collected automatically, either generated by the
                            use of the Service or from the Service infrastructure itself (for example, the duration of a
                            page visit).
                        </li>
                        <li>
                            <strong>Website</strong> refers to welllmake, accessible from
                            <a href="https://welllmake.web.app" target="_blank" rel="noopener noreferrer" className="text-accent underline">
                                welllmake.web.app
                            </a>.
                        </li>
                        <li>
                            <strong>You</strong> means the individual accessing or using the Service, or the company, or
                            other legal entity on behalf of which such individual is accessing or using the Service, as
                            applicable.
                        </li>
                    </ul>

                    <h2 className="text-2xl font-semibold mt-6 mb-4">Collecting and Using Your Personal Data</h2>

                    <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>
                    <h4 className="text-xl font-medium my-2">Personal Data</h4>
                    <p className="mb-4">
                        While using Our Service, We may ask You to provide Us with certain personally identifiable
                        information that can be used to contact or identify You. Personally identifiable information
                        may include, but is not limited to:
                    </p>
                    <ul className="list-disc list-inside space-y-2 opacity-75">
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Usage Data</li>
                    </ul>

                    <h4 className="text-xl font-medium my-2">Usage Data</h4>
                    <p className="mb-4">
                        Usage Data is collected automatically when using the Service. Usage Data may include
                        information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type,
                        browser version, the pages of our Service that You visit, the time and date of Your visit, the
                        time spent on those pages, unique device identifiers, and other diagnostic data.
                    </p>
                    <p className="mb-4">
                        When You access the Service through a mobile device, We may collect certain information
                        automatically, including the type of mobile device You use, Your mobile device unique ID, the
                        IP address of Your mobile device, and other diagnostic data.
                    </p>

                    <h4 className="text-xl font-medium my-2">Tracking Technologies and Cookies</h4>
                    <p className="mb-4">
                        We use Cookies and similar tracking technologies to track the activity on Our Service and
                        store certain information. The technologies We use may include:
                    </p>
                    <ul className="list-disc list-inside space-y-2 opacity-75">
                        <li>
                            <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device.
                            You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being
                            sent.
                        </li>
                        <li>
                            <strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain
                            small electronic files known as web beacons.
                        </li>
                    </ul>
                </div>
            </section>
        </main>

    )
}